useDotenv: true

frameworkVersion: "3"

service: ${env:SERVICE_NAME}

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'test'}
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
    SERVICE_NAME: ${env:SERVICE_NAME}
    TEST_DOMAIN: ${env:TEST_DOMAIN}
    PROD_DOMAIN: ${env:PROD_DOMAIN}
    CERTIFICATE_NAME: ${env:CERTIFICATE_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
#            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
#            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

plugins:
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline
  - serverless-domain-manager # uncomment if you want to use custom domain

custom:
  domain:
    test: ${env:TEST_DOMAIN}
    prod: ${env:PROD_DOMAIN}
  dynamodb:
    stages:
      - test
    start:
        port: 8000
        inMemory: false
        migrate: true
  customDomain:
    domainName: ${self:custom.domain.${self:provider.stage}}
    basePath: 'v1'
    createRoute53Record: true
    stage: ${self:provider.stage}
    certificateName: ${env:CERTIFICATE_NAME}

functions:
  create:
    handler: storage/create.create
    timeout: 30
    events:
      - http:
          path: fingerprint
          method: post
          cors: true

  get:
    handler: storage/get.get
    events:
      - http:
          path: fingerprint/{namespace}/{fingerprint}/{key}
          method: get
          cors: true

resources:
  Resources:
    ThumbmarkStorageTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: fingerprint
            AttributeType: S
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: fingerprint
            KeyType: HASH
          - AttributeName: key
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1  # this is only for testing
          WriteCapacityUnits: 1 # this is only for testing
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: expiresAt
