useDotenv: true

frameworkVersion: "3"

service: ${env:SERVICE_NAME}

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'test'}
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
    ALLOWED_ORIGINS: ${self:custom.allowedOriginsString.${self:provider.stage}}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
#            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
#            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

plugins:
  - serverless-better-credentials
  - serverless-plugin-utils
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-domain-manager # uncomment if you want to use custom domain.
  - serverless-offline

custom:
  domain:
    test: ${env:DOMAIN_TEST}
    prod: ${env:DOMAIN_PROD}
  allowedOriginsString:
    test: ${env:ALLOWED_ORIGINS_TEST}
    prod: ${env:ALLOWED_ORIGINS_PROD}
  dynamodb:
    stages:
      - test
    start:
        port: 8000
        inMemory: false
        migrate: true
  customDomain:
    domainName: ${self:custom.domain.${self:provider.stage}}
    basePath: 'v1'
    createRoute53Record: true
    stage: ${self:provider.stage}
    certificateName: ${env:CERTIFICATE_NAME}

functions:
  create:
    handler: storage/create.create
    timeout: 30
    events:
      - http:
          path: fingerprint
          method: post
          cors:
            origins: ${split(${self:provider.environment.ALLOWED_ORIGINS}, ',')}
            headers:
              - Content-Type
              - X-Amz-Date
              - Content-Type
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  get:
    handler: storage/get.get
    events:
      - http:
          path: fingerprint/{namespace}/{fingerprint}/{key}
          method: get
          cors:
            origins: ${split(${self:provider.environment.ALLOWED_ORIGINS}, ',')}
            headers:
              - Content-Type
              - X-Amz-Date
              - Content-Type
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

resources:
  Conditions:
    IsTest:
      Fn::Equals:
        - ${self:provider.stage}
        - test
    IsProd:
      Fn::Equals:
        - ${self:provider.stage}
        - prod
  Resources:
    ThumbmarkStorageTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        ProvisionedThroughput: # use these three lines when running offline
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
#        ProvisionedThroughput: # use these ten lines when deploying to AWS
#          Fn::If:
#            - IsTest
#            - ReadCapacityUnits: 1
#              WriteCapacityUnits: 1
#            - Ref: 'AWS::NoValue'
#        BillingMode:
#          Fn::If:
#            - IsProd
#            - PAY_PER_REQUEST
#            - PROVISIONED
        AttributeDefinitions:
          - AttributeName: fingerprint
            AttributeType: S
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: fingerprint
            KeyType: HASH
          - AttributeName: key
            KeyType: RANGE
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: expiresAt
